/* This file was automatically generated.  Do not edit! */
void CG_CheckEvents(centity_t *cent);
void CG_EntityEvent(centity_t *cent,vec3_t position);
void CG_ChatBox_AddString(char *chatStr);
const char *CG_GetStringForVoiceSound(const char *s);
extern const char *cg_stringEdVoiceChatTable[MAX_CUSTOM_SIEGE_SOUNDS];
void CG_VehMuzzleFireFX(centity_t *veh,entityState_t *broadcaster);
void CG_CalcVehMuzzle(Vehicle_t *pVeh,centity_t *ent,int muzzleNum);
void CG_G2MarkEvent(entityState_t *es);
void CG_TryPlayCustomSound(vec3_t origin,int entityNum,int channel,const char *soundName);
void CG_PlayDoorSound(centity_t *cent,int type);
void CG_PlayDoorLoopSound(centity_t *cent);
int CG_InClientBitflags(entityState_t *ent,int client);
void DoFall(centity_t *cent,entityState_t *es,int clientNum);
qboolean BG_InKnockDownOnly(int anim);
void CG_GetCTFMessageEvent(entityState_t *es);
void CG_PrintCTFMessage(clientInfo_t *ci,const char *teamName,int ctfMessage);
const char *CG_TeamName(int team);
void CG_ReattachLimb(centity_t *source);
void CG_PainEvent(centity_t *cent,int health);
void CG_LocalTimingBar(int startTime,int duration);
extern vec4_t cg_genericTimerColor;
extern int cg_genericTimerDur;
extern int cg_genericTimerBar;
void CG_ToggleBinoculars(centity_t *cent,int forceZoom);
qboolean CG_ThereIsAMaster(void);
const char *CG_PlaceString(int rank);
extern int cg_vehicleAmmoWarningTime;
extern int cg_vehicleAmmoWarning;
extern int cg_siegeDeathDelay;
extern int cg_siegeDeathTime;
extern char *showPowersName[];
extern vec3_t cg_saberFlashPos;
extern int cg_saberFlashTime;
qboolean CG_InATST(void);
qboolean CG_InFighter(void);
qboolean CG_VehicleWeaponImpact(centity_t *cent);
qboolean WP_SaberBladeUseSecondBladeStyle(saberInfo_t *saber,int bladeNum);
