/* This file was automatically generated.  Do not edit! */
void CG_Cube(vec3_t mins,vec3_t maxs,vec3_t color,float alpha);
void CG_ROFF_NotetrackCallback(centity_t *cent,const char *notetrack);
void CG_AddPacketEntities(qboolean isPortal);
void CG_ManualEntityRender(centity_t *cent);
void CG_G2Animated(centity_t *cent);
void CG_CalcEntityLerpPositions(centity_t *cent);
void CG_AdjustPositionForMover(const vec3_t in,int moverNum,int fromTime,int toTime,vec3_t out);
void CG_Beam(centity_t *cent);
void CG_PlayDoorSound(centity_t *cent,int type);
void CG_PlayDoorLoopSound(centity_t *cent);
extern int CG_BMS_END;
extern int CG_BMS_MID;
extern int CG_BMS_START;
void CG_CreateDistortionTrailPart(centity_t *cent,float scale,vec3_t pos);
qboolean CG_GreyItem(int type,int tag,int plSide);
void CG_G2ServerBoneAngles(centity_t *cent);
void CG_AddBracketedEnt(centity_t *cent);
void CG_AddRadarEnt(centity_t *cent);
extern int cgSiegeEntityRender;
void CG_Disintegration(centity_t *cent,refEntity_t *ent);
extern char *forceHolocronModels[];
void ScaleModelAxis(refEntity_t *ent);
void G2_BoltToGhoul2Model(centity_t *cent,refEntity_t *ent);
void CG_CreateBBRefEnts(entityState_t *s1,vec3_t origin);
void CG_SetGhoul2Info(refEntity_t *ent,centity_t *cent);
void CG_Special(centity_t *cent);
void FX_DrawPortableShield(centity_t *cent);
localEntity_t *FX_AddOrientedLine(vec3_t start,vec3_t end,vec3_t normal,float stScale,float scale,float dscale,float startalpha,float endalpha,float killTime,qhandle_t shader);
void CG_S_UpdateLoopingSounds(int entityNum);
void CG_S_StopLoopingSound(int entityNum,sfxHandle_t sfx);
void CG_S_AddRealLoopingSound(int entityNum,const vec3_t origin,const vec3_t velocity,sfxHandle_t sfx);
void CG_S_AddLoopingSound(int entityNum,const vec3_t origin,const vec3_t velocity,sfxHandle_t sfx);
void CG_SetEntitySoundPosition(centity_t *cent);
void CG_PositionRotatedEntityOnTag(refEntity_t *entity,const refEntity_t *parent,qhandle_t parentModel,char *tagName);
void CG_PositionEntityOnTag(refEntity_t *entity,const refEntity_t *parent,qhandle_t parentModel,char *tagName);
qboolean CG_InFighter(void);
