#pragma once

#include "cg_local.h"
#include "cg_tempwrappers.h"
#include "ui/ui_shared.h"

EXTERNC playerState_t *cgSendPS[MAX_GENTITIES];
EXTERNC itemInfo_t cg_items[MAX_ITEMS];
EXTERNC weaponInfo_t cg_weapons[MAX_WEAPONS];
EXTERNC int cg_numpermanents;
EXTERNC centity_t *cg_permanents[MAX_GENTITIES];
EXTERNC cgs_t cgs;
EXTERNC int cgSiegeRoundBeganTime;
EXTERNC int cg_siegeWinTeam;
EXTERNC int cg_beatingSiegeTime;
EXTERNC char *forceHolocronModels[];
EXTERNC centity_t cg_entities[MAX_GENTITIES];
EXTERNC cg_t cg;
EXTERNC cvar_t *bg_showevents;
EXTERNC vec3_t cg_autoMapAngle;
EXTERNC int cg_autoMapInputTime;
EXTERNC autoMapInput_t cg_autoMapInput;
EXTERNC int cgSiegeRoundTime;
EXTERNC int cgSiegeRoundState;
EXTERNC displayContextDef_t cgDC;

CCALL void CG_FX_CameraShake(void);
CCALL void CG_AutomapInput(void);
CCALL void CG_MapChange(void);
CCALL void _CG_ROFF_NotetrackCallback(int entID,const char *notetrack);
CCALL trajectory_t *CG_GetAngleTrajectory(int entID);
CCALL trajectory_t *CG_GetOriginTrajectory(int entID);
CCALL void CG_GetAngles(int entID,vec3_t out);
CCALL void CG_GetOrigin(int entID,vec3_t out);
CCALL qboolean CG_IncomingConsoleCommand(void);
CCALL void _CG_MouseEvent(int x,int y);
CCALL void CG_PrevInventory_f(void);
CCALL void CG_PrevForcePower_f(void);
CCALL void CG_NextInventory_f(void);
CCALL void CG_NextForcePower_f(void);
CCALL void CG_DestroyAllGhoul2(void);
CCALL void CG_KillCEntityG2(int entNum);
CCALL const char *CG_GetLocationString(const char *loc);
CCALL void BG_VehicleLoadParms(void);
CCALL void WP_SaberLoadParms(void);
CCALL void CG_PmoveClientPointerUpdate();
CCALL void CG_TransitionPermanent(void);
CCALL void CG_Init_CGents(void);
CCALL void CG_Init_CG(void);
CCALL void CG_AssetCache();
CCALL void CG_LoadHudMenu();
CCALL void CG_LoadMenus(const char *menuFile);
CCALL void CG_Text_PaintWithCursor(float x,float y,float scale,vec4_t color,const char *text,int cursorPos,char cursor,int limit,int style,int iMenuFont);
CCALL void CG_SetScoreSelection(void *p);
CCALL qboolean CG_Load_Menu(const char **p);
CCALL void CG_ParseMenu(const char *menuFile);
CCALL qboolean CG_Asset_Parse(int handle);
CCALL char *CG_GetMenuBuffer(const char *filename);
CCALL void CG_StartMusic(qboolean bForceStart);
CCALL void CG_BuildSpectatorString(void);
CCALL void CG_SiegeCountCvars(void);
CCALL int CG_GetTeamNonScoreCount(team_t team);
CCALL int CG_GetClassCount(team_t team,int siegeClass);
CCALL const char *CG_GetStringEdString(char *refSection,char *refName);
CCALL void CG_CacheG2AnimInfo(char *modelName);
CCALL int CG_HandleAppendedSkin(char *modelName);
CCALL const char *CG_ConfigString(int index);
CCALL void CG_ParseSiegeObjectiveStatus(const char *str);
CCALL void CG_PrecacheNPCSounds(const char *str);
CCALL void CG_ParseSiegeState(const char *str);
CCALL void CG_ParseWeatherEffect(const char *str);
CCALL const char *CG_Argv(int arg);
CCALL int CG_LastAttacker(void);
CCALL int CG_CrosshairPlayer(void);
CCALL int CG_RagCallback(int callType);
CCALL void C_G2Mark(void);
CCALL void C_G2Trace(void);
CCALL void C_Trace(void);
CCALL void C_GetLerpData(void);
CCALL void C_GetLerpOrigin(void);
CCALL int C_PointContents(void);
CCALL qboolean CG_NoUseableForce(void);
CCALL void CG_DoCameraShake(vec3_t origin,float intensity,int radius,int time);
CCALL void CG_MiscEnt(void);
CCALL void CG_MiscEnt(void);
CCALL void UI_CleanupGhoul2(void);
CCALL void CG_ROFF_NotetrackCallback(centity_t *cent,const char *notetrack);
CCALL void CG_CalcEntityLerpPositions(centity_t *cent);
CCALL void CG_Shutdown(void);
CCALL void CG_Shutdown(void);
CCALL void CG_Init(int serverMessageNum,int serverCommandSequence,int clientNum);
CCALL void CG_Init(int serverMessageNum,int serverCommandSequence,int clientNum);
CCALL void CG_CleanJetpackGhoul2(void);
CCALL void CG_InitJetpackGhoul2(void);
CCALL void CG_InitItems(void);
CCALL int CM_NumInlineModels();
CCALL int  PC_AddGlobalDefine(char *string);
CCALL int  PC_FreeSourceHandle(int handle);
CCALL int  PC_LoadGlobalDefines(const char* filename );
CCALL int  PC_LoadSourceHandle(const char *filename);
CCALL int  PC_ReadTokenHandle(int handle, pc_token_t *pc_token);
CCALL void PC_RemoveAllGlobalDefines( void );
CCALL int  PC_SourceFileAndLine(int handle, char *filename, int *line);

