/* This file was automatically generated.  Do not edit! */
void CG_GetTeamColor(vec4_t *color);
qboolean CG_DeferMenuScript(char **args);
void CG_RunMenuScript(char **args);
void CG_ShowResponseHead(void);
int CG_ClientNumFromName(const char *p);
CCALL void CG_KeyEvent(int key,qboolean down);
CCALL void CG_EventHandling(int type);
void CG_ShowTeamMenu();
void CG_HideTeamMenu();
void CG_MouseEvent(int x,int y);
void CG_OwnerDraw(float x,float y,float w,float h,float text_x,float text_y,int ownerDraw,int ownerDrawFlags,int align,float special,float scale,vec4_t color,qhandle_t shader,int textStyle,int font);
void CG_DrawMedal(int ownerDraw,rectDef_t *rect,float scale,vec4_t color,qhandle_t shader);
void CG_DrawTeamSpectators(rectDef_t *rect,float scale,vec4_t color,qhandle_t shader);
void CG_DrawNewTeamInfo(rectDef_t *rect,float text_x,float text_y,float scale,vec4_t color,qhandle_t shader);
const char *CG_GetLocationString(const char *loc);
CCALL int MenuFontToHandle_CG(int iMenuFont);
const char *CG_GetGameStatusText(void);
const char *CG_GetKillerText(void);
qboolean CG_OwnerDrawVisible(int flags);
qboolean CG_YourTeamHasFlag(void);
qboolean CG_OtherTeamHasFlag(void);
float CG_GetValue(int ownerDraw);
qhandle_t CG_StatusHandle(int task);
int CG_GetSelectedPlayer();
extern displayContextDef_t cgDC;
