/* This file was automatically generated.  Do not edit! */
void CG_CheckThirdPersonAlpha(centity_t *cent,refEntity_t *legs);
extern vec3_t cameraCurLoc;
extern vec3_t cg_crosshairPos;
float CG_RadiusForCent(centity_t *cent);
int BG_EmplacedView(vec3_t baseAngles,vec3_t angles,float *newYaw,float constraint);
extern int cg_lastHyperSpaceEffectTime;
void CG_CleanJetpackGhoul2(void);
void CG_InitJetpackGhoul2(void);
extern void *cg_g2JetpackInstance;
void CG_DestroyNPCClient(clientInfo_t **ci);
void CG_CreateNPCClient(clientInfo_t **ci);
void CG_Player(centity_t *cent);
void CG_G2Animated(centity_t *cent);
qboolean CG_VehicleAttachDroidUnit(centity_t *droidCent,refEntity_t *legs);
qboolean CG_VehicleShouldDrawShields(centity_t *vehCent);
void CG_G2AnimEntModelLoad(centity_t *cent);
extern playerState_t *cgSendPS[MAX_GENTITIES];
void G_CreateFighterNPC(Vehicle_t **pVeh,const char *strType);
void G_CreateWalkerNPC(Vehicle_t **pVeh,const char *strAnimalType);
void G_CreateSpeederNPC(Vehicle_t **pVeh,const char *strType);
void G_CreateAnimalNPC(Vehicle_t **pVeh,const char *strAnimalType);
void CG_HandleNPCSounds(centity_t *cent);
void CG_CacheG2AnimInfo(char *modelName);
void BG_GetVehicleSkinName(char *skinname,int len);
void BG_GetVehicleModelName(char *modelName,const char *vehicleName,size_t len);
int CG_HandleAppendedSkin(char *modelName);
qboolean CG_ThereIsAMaster(void);
extern char *forceHolocronModels[];
void CG_AddRandomLightning(vec3_t start,vec3_t end);
void CG_AddLightningBeam(vec3_t start,vec3_t end);
void CG_DrawPlayerSphere(centity_t *cent,vec3_t origin,float scale,int shader);
void CG_AddSaberBlade(centity_t *cent,centity_t *scent,refEntity_t *saber,int renderfx,int modelIndex,int saberNum,int bladeNum,vec3_t origin,vec3_t angles,qboolean fromSaber,qboolean dontDraw);
qboolean BG_SuperBreakWinAnim(int anim);
void CG_SaberCompWork(vec3_t start,vec3_t end,centity_t *owner,int saberNum,int bladeNum);
void CG_AddGhoul2Mark(int shader,float size,vec3_t start,vec3_t end,int entnum,vec3_t entposition,float entangle,void *ghoul2,vec3_t scale,int lifeTime);
void CG_G2SaberEffects(vec3_t start,vec3_t end,centity_t *owner);
qboolean CG_G2TraceCollide(trace_t *tr,vec3_t const mins,vec3_t const maxs,const vec3_t lastValidStart,const vec3_t lastValidEnd);
void CG_CreateSaberMarks(vec3_t start,vec3_t end,vec3_t normal);
markPoly_t *CG_AllocMark();
void CG_GetTagWorldPosition(refEntity_t *model,char *tag,vec3_t pos,matrix3_t axis);
void CG_DoSaber(vec3_t origin,vec3_t dir,float length,float lengthMax,float radius,saber_colors_t color,int rfx,qboolean doLight);
int CG_LightVerts(vec3_t normal,int numVerts,polyVert_t *verts);
void CG_PlayerHitFX(centity_t *cent);
void CG_DrawPlayerShield(centity_t *cent,vec3_t origin);
void CG_PlayerShieldHit(int entitynum,vec3_t dir,int amount);
void CG_AddRefEntityWithPowerups(refEntity_t *ent,entityState_t *state,int team);
int CG_IsMindTricked(int trickIndex1,int trickIndex2,int trickIndex3,int trickIndex4,int client);
qboolean CG_G2PlayerHeadAnims(centity_t *cent);
void CG_G2ServerBoneAngles(centity_t *cent);
qboolean CG_RagDoll(centity_t *cent,vec3_t forcedAngles);
#if defined(_RAG_BOLT_TESTING)
void CG_TempTestFunction(centity_t *cent,vec3_t forcedAngles);
#endif
void CG_Rag_Trace(trace_t *result,const vec3_t start,const vec3_t mins,const vec3_t maxs,const vec3_t end,int skipNumber,int mask);
void CG_G2SetBoneAngles(void *ghoul2,int modelIndex,const char *boneName,const vec3_t angles,const int flags,const int up,const int right,const int forward,qhandle_t *modelList,int blendTime,int currentTime);
qboolean PM_WalkingAnim(int anim);
qboolean PM_RunningAnim(int anim);
qboolean BG_SaberStanceAnim(int anim);
qboolean CG_InRollAnim(centity_t *cent);
qboolean CG_InRoll(centity_t *cent);
void CG_TriggerAnimSounds(centity_t *cent);
void CG_PlayerAnimEvents(int animFileIndex,int eventFileIndex,qboolean torso,int oldFrame,int frame,int entNum);
void CG_PlayerAnimEventDo(centity_t *cent,animevent_t *animEvent);
void CG_LoadDeferredPlayers(void);
void CG_ActualLoadDeferredPlayers(void);
extern qboolean cgQueueLoad;
void CG_NewClientInfo(int clientNum,qboolean entitiesInitialized);
void WP_SetSaber(int entNum,saberInfo_t *sabers,int saberNum,const char *saberName);
void CG_ResetPlayerEntity(centity_t *cent);
void CG_LoadClientInfo(clientInfo_t *ci);
void CG_LoadCISounds(clientInfo_t *ci,qboolean modelloaded);
int CG_G2EvIndexForModel(void *g2,int animIndex);
int CG_G2SkelForModel(void *g2);
qboolean BG_ValidateSkinForTeam(const char *modelName,char *skinName,int team,float *colors);
qboolean BG_IsValidCharacterModel(const char *modelName,const char *skinName);
qboolean CG_ParseSurfsFile(const char *modelName,const char *skinName,char *surfOff,char *surfOn);
sfxHandle_t CG_CustomSound(int clientNum,const char *soundName);
void CG_Disintegration(centity_t *cent,refEntity_t *ent);
extern const char *cg_customDuelSoundNames[MAX_CUSTOM_DUEL_SOUNDS];
extern const char *cg_customJediSoundNames[MAX_CUSTOM_JEDI_SOUNDS];
extern const char *cg_customExtraSoundNames[MAX_CUSTOM_EXTRA_SOUNDS];
extern const char *cg_customCombatSoundNames[MAX_CUSTOM_COMBAT_SOUNDS];
extern char *cg_customSoundNames[MAX_CUSTOM_SOUNDS];
extern stringID_table_t animTable[MAX_ANIMATIONS+1];
qboolean WP_SaberBladeUseSecondBladeStyle(saberInfo_t *saber,int bladeNum);
qboolean CG_InFighter(void);
void CG_AddBracketedEnt(centity_t *cent);
void CG_AddRadarEnt(centity_t *cent);
extern int cgSiegeTeam2PlShader;
extern int cgSiegeTeam1PlShader;
