/* This file was automatically generated.  Do not edit! */
void CG_ExecuteNewServerCommands(int latestSequence);
int svcmdcmp_cg(const void *a,const void *b);
void CG_ChatBox_AddString(char *chatStr);
void CG_ParseSiegeExtendedData(void);
void CG_SiegeBriefingDisplay(int team,int dontshow);
void CG_CheckSVStringEdRef(char *buf,const char *str);
void CG_KillCEntityInstances(void);
void CG_KillCEntityG2(int entNum);
extern int cg_siegeWinTeam;
extern int cg_beatingSiegeTime;
void CG_ParseSiegeState(const char *str);
void CG_ParseWeatherEffect(const char *str);
void CG_ParseSiegeObjectiveStatus(const char *str);
extern int cgSiegeRoundTime;
extern int cgSiegeRoundState;
void SetDuelistHealthsFromConfigString(const char *str);
void CG_CacheG2AnimInfo(char *modelName);
int CG_HandleAppendedSkin(char *modelName);
void CG_HandleNPCSounds(centity_t *cent);
void CG_PrecacheNPCSounds(const char *str);
void SetCustomSoundForType(clientInfo_t *ci,int setType,int index,sfxHandle_t sfx);
extern const char *cg_customDuelSoundNames[MAX_CUSTOM_DUEL_SOUNDS];
extern const char *cg_customJediSoundNames[MAX_CUSTOM_JEDI_SOUNDS];
extern const char *cg_customExtraSoundNames[MAX_CUSTOM_EXTRA_SOUNDS];
extern const char *cg_customCombatSoundNames[MAX_CUSTOM_COMBAT_SOUNDS];
extern char *cg_customSoundNames[MAX_CUSTOM_SOUNDS];
void CG_ShaderStateChanged(void);
void CG_SetConfigValues(void);
void CG_ParseServerinfo(void);
