/*
===========================================================================
Copyright (C) 1999 - 2005, Id Software, Inc.
Copyright (C) 2000 - 2013, Raven Software, Inc.
Copyright (C) 2001 - 2013, Activision, Inc.
Copyright (C) 2013 - 2015, OpenJK contributors

This file is part of the OpenJK source code.

OpenJK is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
===========================================================================
*/

#ifdef XCVAR_PROTO
	#define XCVAR_DEF( name, defVal, update, flags, announce, desc) EXTERNC cvar_t *name;
#endif
#ifdef XCVAR_DECL
	#define XCVAR_DEF( name, defVal, update, flags, announce, desc) cvar_t *name;
#endif
#ifdef XCVAR_LIST
	#define XCVAR_DEF( name, defVal, update, flags, announce, desc) name = Cvar_Get( #name , defVal , flags , "" );
#endif

//XCVAR_DEF( com_optvehtrace,				"0",			NULL,				CVAR_NONE,										qtrue )
//XCVAR_DEF( d_altRoutes,					"0",			NULL,				CVAR_CHEAT,										qfalse )
//XCVAR_DEF( d_patched,					"0",			NULL,				CVAR_CHEAT,										qfalse )
//XCVAR_DEF( g_engineModifications,		"1",			NULL,				CVAR_ARCHIVE,									qfalse )
//XCVAR_DEF( sv_fps,						"40",			NULL,				CVAR_ARCHIVE|CVAR_SERVERINFO,					qtrue )
//XCVAR_DEF( sv_maxclients,				"8",			NULL,				CVAR_SERVERINFO|CVAR_LATCH|CVAR_ARCHIVE,		qfalse )

#define STR(x) #x

XCVAR_DEF( timelimit                             , "0"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE|CVAR_NORESTART         , qtrue   , ""                                                                               )
XCVAR_DEF( sv_zombietime                         , "2"                       , NULL, CVAR_TEMP                                           , qfalse  , ""                                                                               )
XCVAR_DEF( sv_timeout                            , "200"                     , NULL, CVAR_TEMP                                           , qfalse  , ""                                                                               )
XCVAR_DEF( sv_snapsPolicy                        , "1"                       , NULL, CVAR_ARCHIVE_ND                                     , qfalse  , "Determines which policy of enforcement is used for client's \"snaps\" cvar"     )
XCVAR_DEF( sv_snapsMin                           , "10"                      , NULL, CVAR_ARCHIVE_ND                                     , qfalse  , ""                                                                               ) // 1 <=> sv_snapsMax
XCVAR_DEF( sv_snapsMax                           , "40"                      , NULL, CVAR_ARCHIVE_ND                                     , qfalse  , ""                                                                               ) // sv_snapsMin <=> sv_fps
XCVAR_DEF( sv_showloss                           , "0"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( sv_showghoultraces                    , "0"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( sv_serverid                           , "0"                       , NULL, CVAR_SYSTEMINFO | CVAR_ROM                          , qfalse  , ""                                                                               )
XCVAR_DEF( sv_referencedPaks                     , ""                        , NULL, CVAR_SYSTEMINFO | CVAR_ROM                          , qfalse  , ""                                                                               )
XCVAR_DEF( sv_referencedPakNames                 , ""                        , NULL, CVAR_SYSTEMINFO | CVAR_ROM                          , qfalse  , ""                                                                               )
XCVAR_DEF( sv_reconnectlimit                     , "3"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( sv_ratePolicy                         , "1"                       , NULL, CVAR_ARCHIVE_ND                                     , qfalse  , "Determines which policy of enforcement is used for client's \"rate\" cvar"      )
XCVAR_DEF( sv_pure                               , "0"                       , NULL, CVAR_SYSTEMINFO                                     , qfalse  , "Pure server"                                                                    )
XCVAR_DEF( sv_privatePassword                    , ""                        , NULL, CVAR_TEMP                                           , qfalse  , ""                                                                               )
XCVAR_DEF( sv_privateClients                     , "0"                       , NULL, CVAR_SERVERINFO                                     , qfalse  , "Number of reserved client slots available with password"                        )
XCVAR_DEF( sv_paks                               , ""                        , NULL, CVAR_SYSTEMINFO | CVAR_ROM                          , qfalse  , ""                                                                               )
XCVAR_DEF( sv_pakNames                           , ""                        , NULL, CVAR_SYSTEMINFO | CVAR_ROM                          , qfalse  , ""                                                                               )
XCVAR_DEF( sv_padPackets                         , "0"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( sv_minRate                            , "0"                       , NULL, CVAR_ARCHIVE_ND | CVAR_SERVERINFO                   , qfalse  , "Min bandwidth rate allowed on server. Use 0 for unlimited."                     )
XCVAR_DEF( sv_minPing                            , "0"                       , NULL, CVAR_ARCHIVE_ND | CVAR_SERVERINFO                   , qfalse  , ""                                                                               )
XCVAR_DEF( sv_maxclients                         , "8"                       , NULL, CVAR_SERVERINFO | CVAR_LATCH                        , qfalse  , "Max. connected clients"                                                         )
XCVAR_DEF( sv_maxRate                            , "0"                       , NULL, CVAR_ARCHIVE_ND | CVAR_SERVERINFO                   , qfalse  , "Max bandwidth rate allowed on server. Use 0 for unlimited."                     )
XCVAR_DEF( sv_maxPing                            , "0"                       , NULL, CVAR_ARCHIVE_ND | CVAR_SERVERINFO                   , qfalse  , ""                                                                               )
XCVAR_DEF( sv_master5                            , ""                        , NULL, CVAR_ARCHIVE_ND|CVAR_PROTECTED                      , qfalse  , ""                                                                               )
XCVAR_DEF( sv_master4                            , ""                        , NULL, CVAR_ARCHIVE_ND|CVAR_PROTECTED                      , qfalse  , ""                                                                               )
XCVAR_DEF( sv_master3                            , ""                        , NULL, CVAR_ARCHIVE_ND|CVAR_PROTECTED                      , qfalse  , ""                                                                               )
XCVAR_DEF( sv_master2                            , ""                        , NULL, CVAR_PROTECTED                                      , qfalse  , ""                                                                               )
XCVAR_DEF( sv_master1                            , ""                        , NULL, CVAR_PROTECTED                                      , qfalse  , ""                                                                               )
XCVAR_DEF( sv_mapChecksum                        , ""                        , NULL, CVAR_ROM                                            , qfalse  , ""                                                                               )
XCVAR_DEF( sv_legacyFixes                        , "1"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( sv_lanForceRate                       , "1"                       , NULL, CVAR_ARCHIVE_ND                                     , qfalse  , ""                                                                               )
XCVAR_DEF( sv_killserver                         , "0"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( sv_keywords                           , ""                        , NULL, CVAR_SERVERINFO                                     , qfalse  , ""                                                                               )
XCVAR_DEF( sv_hostname                           , "*Jedi*"                  , NULL, CVAR_SERVERINFO | CVAR_ARCHIVE                      , qfalse  , "The name of the server that is displayed in the serverlist"                     )
XCVAR_DEF( sv_fps                                , "40"                      , NULL, CVAR_SERVERINFO                                     , qfalse  , "Server frames per second"                                                       )
XCVAR_DEF( sv_floodProtect                       , "1"                       , NULL, CVAR_ARCHIVE | CVAR_SERVERINFO                      , qfalse  , "Protect against flooding of server commands"                                    )
XCVAR_DEF( sv_filterCommands                     , "1"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( sv_clientRate                         , "50000"                   , NULL, CVAR_ARCHIVE_ND                                     , qfalse  , ""                                                                               )
XCVAR_DEF( sv_cheats                             , "1"                       , NULL, CVAR_SYSTEMINFO | CVAR_ROM                          , qfalse  , "Allow cheats on server if set to 1"                                             )
XCVAR_DEF( sv_banFile                            , "serverbans.dat"          , NULL, CVAR_ARCHIVE                                        , qfalse  , "File to use to store bans and exceptions"                                       )
XCVAR_DEF( sv_autoDemoMaxMaps                    , "0"                       , NULL, CVAR_ARCHIVE_ND                                     , qfalse  , ""                                                                               )
XCVAR_DEF( sv_autoDemoBots                       , "0"                       , NULL, CVAR_ARCHIVE_ND                                     , qfalse  , "Record server-side demos for bots"                                              )
XCVAR_DEF( sv_autoDemo                           , "0"                       , NULL, CVAR_ARCHIVE_ND | CVAR_SERVERINFO                   , qfalse  , "Automatically take server-side demos"                                           )
XCVAR_DEF( sv_allowDownload                      , "0"                       , NULL, CVAR_SERVERINFO                                     , qfalse  , "Allow clients to download mod files via UDP from the server"                    )
XCVAR_DEF( rconPassword                          , ""                        , NULL, CVAR_TEMP                                           , qfalse  , ""                                                                               )
XCVAR_DEF( protocol                              , STR(PROTOCOL_VERSION)     , NULL, CVAR_SERVERINFO | CVAR_ROM                          , qfalse  , ""                                                                               )
XCVAR_DEF( pmove_msec                            , "8"                       , NULL, CVAR_SYSTEMINFO|CVAR_ARCHIVE                        , qtrue   , ""                                                                               )
XCVAR_DEF( pmove_float                           , "0"                       , NULL, CVAR_SYSTEMINFO|CVAR_ARCHIVE                        , qtrue   , ""                                                                               )
XCVAR_DEF( pmove_fixed                           , "0"                       , NULL, CVAR_SYSTEMINFO|CVAR_ARCHIVE                        , qtrue   , ""                                                                               )
XCVAR_DEF( nextmap                               , ""                        , NULL, CVAR_TEMP                                           , qfalse  , ""                                                                               )
XCVAR_DEF( mapname                               , "nomap"                   , NULL, CVAR_SERVERINFO | CVAR_ROM                          , qfalse  , ""                                                                               )
XCVAR_DEF( gamename                              , GAMEVERSION               , NULL, CVAR_SERVERINFO|CVAR_ROM                            , qfalse  , ""                                                                               )
XCVAR_DEF( gamedate                              , SOURCE_DATE               , NULL, CVAR_ROM                                            , qfalse  , ""                                                                               )
XCVAR_DEF( g_weaponRespawn                       , "5"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_weaponDisable                       , "0"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE|CVAR_LATCH             , qtrue   , ""                                                                               )
XCVAR_DEF( g_warmup                              , "20"                      , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_voteDelay                           , "3000"                    , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( g_userinfoValidate                    , "25165823"                , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_useWhileThrowing                    , "1"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_timeouttospec                       , "70"                      , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_teamForceBalance                    , "0"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_teamAutoJoin                        , "0"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_synchronousClients                  , "0"                       , NULL, CVAR_SYSTEMINFO                                     , qfalse  , ""                                                                               )
XCVAR_DEF( g_stepSlideFix                        , "1"                       , NULL, CVAR_SERVERINFO                                     , qtrue   , ""                                                                               )
XCVAR_DEF( g_statLogFile                         , "statlog.log"             , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_statLog                             , "0"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_speed                               , "250"                     , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_spawnInvulnerability                , "3000"                    , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_smoothClients                       , "1"                       , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( g_slowmoDuelEnd                       , "0"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_siegeTeamSwitch                     , "1"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_siegeTeam2                          , "none"                    , NULL, CVAR_ARCHIVE|CVAR_SERVERINFO                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_siegeTeam1                          , "none"                    , NULL, CVAR_ARCHIVE|CVAR_SERVERINFO                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_siegeRespawn                        , "20"                      , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_showDuelHealths                     , "0"                       , NULL, CVAR_SERVERINFO                                     , qfalse  , ""                                                                               )
XCVAR_DEF( g_securityLog                         , "1"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_saberWallDamageScale                , "0.4"                     , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( g_saberTraceSaberFirst                , "0"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_saberRestrictForce                  , "0"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_saberRealisticCombat                , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( g_saberLocking                        , "1"                       , NULL, CVAR_SERVERINFO                                     , qtrue   , ""                                                                               )
XCVAR_DEF( g_saberLockRandomNess                 , "2"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_saberLockFactor                     , "2"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_saberDmgVelocityScale               , "0"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_saberDmgDelay_Wound                 , "0"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_saberDmgDelay_Idle                  , "350"                     , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_saberDebugPrint                     , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( g_saberDebugBox                       , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( g_saberDamageScale                    , "1"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_saberBladeFaces                     , "1"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_restarted                           , "0"                       , NULL, CVAR_ROM                                            , qfalse  , ""                                                                               )
XCVAR_DEF( g_randFix                             , "1"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_privateDuel                         , "1"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_powerDuelStartHealth                , "150"                     , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_powerDuelEndHealth                  , "90"                      , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_password                            , ""                        , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( g_npcspskill                          , "0"                       , NULL, CVAR_ARCHIVE|CVAR_INTERNAL                          , qfalse  , ""                                                                               )
XCVAR_DEF( g_noSpecMove                          , "0"                       , NULL, CVAR_SERVERINFO                                     , qtrue   , ""                                                                               )
XCVAR_DEF( g_needpass                            , "0"                       , NULL, CVAR_SERVERINFO | CVAR_ROM                          , qfalse  , "Server needs password to join"                                                  )
XCVAR_DEF( g_motd                                , ""                        , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( g_maxHolocronCarry                    , "3"                       , NULL, CVAR_SERVERINFO|CVAR_LATCH                          , qfalse  , ""                                                                               )
XCVAR_DEF( g_maxGameClients                      , "0"                       , NULL, CVAR_SERVERINFO|CVAR_LATCH|CVAR_ARCHIVE             , qfalse  , ""                                                                               )
XCVAR_DEF( g_maxForceRank                        , "7"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE|CVAR_LATCH             , qfalse  , ""                                                                               )
XCVAR_DEF( g_maxConnPerIP                        , "3"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_logSync                             , "0"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_logClientInfo                       , "0"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_log                                 , "games.log"               , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_locationBasedDamage                 , "1"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_knockback                           , "1000"                    , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_jediVmerc                           , "0"                       , NULL, CVAR_SERVERINFO|CVAR_LATCH|CVAR_ARCHIVE             , qtrue   , ""                                                                               )
XCVAR_DEF( g_inactivity                          , "0"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_gravity                             , "800"                     , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_gametype                            , "0"                       , NULL, CVAR_SERVERINFO | CVAR_LATCH                        , qfalse  , "Server gametype value"                                                          )
XCVAR_DEF( g_g2TraceLod                          , "3"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_friendlySaber                       , "0"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_friendlyFire                        , "0"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_fraglimitVoteCorrection             , "1"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_forceRespawn                        , "60"                      , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_forceRegenTime                      , "200"                     , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_forcePowerDisable                   , "0"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE|CVAR_LATCH             , qtrue   , ""                                                                               )
XCVAR_DEF( g_forceDodge                          , "1"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_forceClientUpdateRate               , "250"                     , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( g_forceBasedTeams                     , "0"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE|CVAR_LATCH             , qfalse  , ""                                                                               )
XCVAR_DEF( g_filterBan                           , "1"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_ff_objectives                       , "0"                       , NULL, CVAR_CHEAT|CVAR_NORESTART                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_duelWeaponDisable                   , "1"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE|CVAR_LATCH             , qtrue   , ""                                                                               )
XCVAR_DEF( g_doWarmup                            , "0"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_dismember                           , "0"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_disableServerG2                     , "0"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_debugServerSkel                     , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( g_debugSaberLocks                     , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( g_debugMove                           , "0"                       , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( g_debugMelee                          , "0"                       , NULL, CVAR_SERVERINFO                                     , qtrue   , ""                                                                               )
XCVAR_DEF( g_debugDamage                         , "0"                       , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( g_debugAlloc                          , "0"                       , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( g_charRestrictRGB                     , "1"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_botsFile                            , ""                        , NULL, CVAR_INIT|CVAR_ROM                                  , qfalse  , ""                                                                               )
XCVAR_DEF( g_banIPs                              , ""                        , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_autoMapCycle                        , "0"                       , NULL, CVAR_ARCHIVE|CVAR_NORESTART                         , qtrue   , ""                                                                               )
XCVAR_DEF( g_austrian                            , "0"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_armBreakage                         , "0"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_antiFakePlayer                      , "1"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_allowVote                           , "-1"                      , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_allowTeamVote                       , "1"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( g_allowNPC                            , "1"                       , NULL, CVAR_CHEAT                                          , qtrue   , ""                                                                               )
XCVAR_DEF( g_allowHighPingDuelist                , "1"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( g_allowDuelSuicide                    , "1"                       , NULL, CVAR_ARCHIVE                                        , qtrue   , ""                                                                               )
XCVAR_DEF( g_adaptRespawn                        , "1"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( fraglimit                             , "20"                      , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE|CVAR_NORESTART         , qtrue   , ""                                                                               )
XCVAR_DEF( duel_fraglimit                        , "10"                      , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE|CVAR_NORESTART         , qtrue   , ""                                                                               )
XCVAR_DEF( dmflags                               , "0"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE                        , qtrue   , ""                                                                               )
XCVAR_DEF( developer                             , "0"                       , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( dedicated                             , "0"                       , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( d_siegeSeekerNPC                      , "0"                       , NULL, CVAR_CHEAT                                          , qtrue   , ""                                                                               )
XCVAR_DEF( d_saberStanceDebug                    , "0"                       , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( d_saberSPStyleDamage                  , "1"                       , NULL, CVAR_ARCHIVE                                        , qfalse  , ""                                                                               )
XCVAR_DEF( d_saberKickTweak                      , "1"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( d_saberInterpolate                    , "0"                       , NULL, CVAR_CHEAT                                          , qtrue   , ""                                                                               )
XCVAR_DEF( d_saberGhoul2Collision                , "1"                       , NULL, CVAR_CHEAT                                          , qtrue   , ""                                                                               )
XCVAR_DEF( d_saberCombat                         , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( d_saberBoxTraceSize                   , "0"                       , NULL, CVAR_CHEAT                                          , qtrue   , ""                                                                               )
XCVAR_DEF( d_saberAlwaysBoxTrace                 , "0"                       , NULL, CVAR_CHEAT                                          , qtrue   , ""                                                                               )
XCVAR_DEF( d_projectileGhoul2Collision           , "1"                       , NULL, CVAR_CHEAT                                          , qtrue   , ""                                                                               )
XCVAR_DEF( d_powerDuelPrint                      , "0"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )
XCVAR_DEF( d_perPlayerGhoul2                     , "0"                       , NULL, CVAR_CHEAT                                          , qtrue   , ""                                                                               )
XCVAR_DEF( d_npcfreeze                           , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( d_npcaiming                           , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( d_npcai                               , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( d_noroam                              , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( d_noIntermissionWait                  , "0"                       , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( d_noGroupAI                           , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( d_break                               , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( d_asynchronousGroupAI                 , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( d_JediAI                              , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( capturelimit                          , "8"                       , NULL, CVAR_SERVERINFO|CVAR_ARCHIVE|CVAR_NORESTART         , qtrue   , ""                                                                               )
XCVAR_DEF( bot_wp_visconnect                     , "1"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( bot_wp_info                           , "1"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( bot_wp_edit                           , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( bot_wp_distconnect                    , "1"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( bot_wp_clearweight                    , "1"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( bot_pvstype                           , "1"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( bot_normgpath                         , "1"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( bot_nogoals                           , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( bot_minplayers                        , "0"                       , NULL, CVAR_NONE                                           , qfalse  , ""                                                                               )
XCVAR_DEF( bot_honorableduelacceptance           , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( bot_getinthecarrr                     , "0"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( bot_forgimmick                        , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( bot_forcepowers                       , "1"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( bot_debugmessages                     , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( bot_camp                              , "1"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( bot_attachments                       , "1"                       , NULL, 0                                                   , qfalse  , ""                                                                               )
XCVAR_DEF( bg_fighterAltControl                  , "0"                       , NULL, CVAR_SYSTEMINFO                                     , qtrue   , ""                                                                               )
XCVAR_DEF( RMG                                   , "0"                       , NULL, CVAR_NONE                                           , qtrue   , ""                                                                               )

XCVAR_DEF( d_altRoutes                           , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( d_patched                             , "0"                       , NULL, CVAR_CHEAT                                          , qfalse  , ""                                                                               )
XCVAR_DEF( com_optvehtrace                       , "0"                       , NULL, 0                                                   , qfalse  , ""                                                                               )


#undef XCVAR_DEF
